/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'john' at '7/30/15 8:40 PM' with Gradle 2.4
 *
 * @author john, @date 7/30/15 8:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
