/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'jengelman' at '7/24/14 11:16 AM' with Gradle 2.0
 *
 * @author jengelman, @date 7/24/14 11:16 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
