/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'jengelman' at '7/24/14 11:16 AM' with Gradle 2.0
 *
 * @author jengelman, @date 7/24/14 11:16 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
